export const CHECK_FETCH = 'CHECK_FETCH';
export const DELETE_BTN = 'DELETE_BTN';
//new
export const CHECKOFFER_CHANGE = 'CHECKOFFER_CHANGE';
export const CHECKDESCRIPTION_CHANGE = 'CHECKDESCRIPTION_CHANGE';
export const CHECKEXPIRE_CHANGE = 'CHECKEXPIRE_CHANGE';
export const CHECKINFO_CHANGE = 'CHECKINFO_CHANGE';
export const CHECKVALUE_CHANGE = 'CHECKVALUE_CHANGE';
export const BTNVALUE_CHANGE = 'BTNVALUE_CHANGE';
export const BTNNAME_CHANGE = 'BTNNAME_CHANGE';
export const BTNNOTE_CHANGE = 'BTNNOTE_CHANGE';
export const BTNCOLOR_CHOOSEN = 'BTNCOLOR_CHOOSEN';
export const BTNICON_CHOOSEN = 'BTNICON_CHOOSEN';
